
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diliru
 */
public class Member_Book_Details extends javax.swing.JFrame {
    
    
    String book;
    String UserName;
    /**
     * Creates new form BooDetails_JFrame
     */
    public Member_Book_Details() {
        //initComponents();
    }

    public Member_Book_Details(String currentUser) {
       //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       
       this.UserName=currentUser;
       initComponents();
       
    
    
    }
    
    String id;
    String available;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBookAuthor = new javax.swing.JLabel();
        lblAvaialability = new javax.swing.JLabel();
        txtBookAuthor = new javax.swing.JTextField();
        btnOkay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblBookId = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        lblBookName = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBookReserve = new javax.swing.JButton();
        txtBookAvaialability = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        lblTitle.setText("Book Details");

        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addGap(18, 18, 18)
                .addComponent(lblClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(lblClose))
                    .addComponent(lblMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        lblBookAuthor.setForeground(new java.awt.Color(255, 255, 255));
        lblBookAuthor.setText("Author");

        lblAvaialability.setForeground(new java.awt.Color(255, 255, 255));
        lblAvaialability.setText("Avaialability");

        txtBookAuthor.setEditable(false);

        btnOkay.setText("Okay");
        btnOkay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkayMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        lblBookId.setForeground(new java.awt.Color(255, 255, 255));
        lblBookId.setText("Book ID");

        txtBookId.setEditable(false);

        lblBookName.setForeground(new java.awt.Color(255, 255, 255));
        lblBookName.setText("Enter Book Name");

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        btnBookReserve.setText("Reserve Book");
        btnBookReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookReserveMouseClicked(evt);
            }
        });

        txtBookAvaialability.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookAuthor)
                            .addComponent(lblAvaialability)
                            .addComponent(lblBookName)
                            .addComponent(lblBookId)
                            .addComponent(btnCancel))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBookReserve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                                .addComponent(btnOkay))
                            .addComponent(txtBookId)
                            .addComponent(txtBookAuthor)
                            .addComponent(txtBookName)
                            .addComponent(txtBookAvaialability))))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookName))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookId))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookAuthor)
                    .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAvaialability))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtBookAvaialability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOkay)
                    .addComponent(btnBookReserve))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void btnOkayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseClicked
                
                Member_home home= new Member_home(UserName);
                home.setVisible(true);
                home.pack();
                home.setLocationRelativeTo(null);
                home.lblHomeUserName.setText("Welcome");
                home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
       
    }//GEN-LAST:event_btnOkayMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        txtBookName.setText("");
        txtBookId.setText("");
        txtBookAuthor.setText("");
        txtBookAvaialability.setText("");
        
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        
        book=txtBookName.getText();
        
        String query="SELECT * FROM `books` WHERE `book_name` =?";
        
        try {
            ps=MyConnection.getConnetction().prepareStatement(query);
            
            ps.setString(1, book);
            
            
            rs = ps.executeQuery();
            
            
            
            if(rs.next()){
                 id = rs.getString("book_id");
                String author = rs.getString("book_author");
                 available = rs.getString("book_status");
                
                txtBookId.setText(id);
                txtBookAuthor.setText(author);
                txtBookAvaialability.setText(available);
                
                
            }
            else{
                JOptionPane.showMessageDialog(null,"This book is not available");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnBookReserveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookReserveMouseClicked
       
       if(available.equals("available")){ 
        
                    PreparedStatement pst;
                    ResultSet rst;

                    String queryt="SELECT * FROM `the_app_users` WHERE `u_uname` =?";

                    try {
                        pst=MyConnection.getConnetction().prepareStatement(queryt);
                        pst.setString(1, UserName);
                        rst = pst.executeQuery();

                    if(rst.next()){
                        String b_Books=rst.getString("reserved_books");
                        String memberID=rst.getString("u_id");
                        
                        int num3 = Integer.valueOf(b_Books);
        
                            if(num3<2){
                                
                    String querymt="UPDATE `books` SET `book_status`=? WHERE `book_name`= '"+book+"'";
        
                    PreparedStatement pstmt = null;
                    try { 
                
                     pstmt = MyConnection.getConnetction().prepareStatement(querymt);
                     pstmt.setString(1, "reserved");
                     pstmt.executeUpdate();
               
                    } catch (SQLException ex) {
                    Logger.getLogger(Admin_Search_Book_Details.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    
                    
                    
                    
                        
                        int num2=num3+1;
                        
                        String reserve= Integer.toString(num2);
                        
                        String querytt="UPDATE `the_app_users` SET `reserved_books`=? WHERE `u_uname`= '"+UserName+"'";
        
                    PreparedStatement psttt = null;
                    try { 
                
                     psttt = MyConnection.getConnetction().prepareStatement(querytt);
                     psttt.setString(1, reserve);
                     psttt.executeUpdate();
               
                    } catch (SQLException ex) {
                    Logger.getLogger(Admin_Search_Book_Details.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    
                    
                PreparedStatement ps2;
                String query2="INSERT INTO `reserved_books`(`book_id`, `member_id`) VALUES (?,?)";
                    
                ps2 = MyConnection.getConnetction().prepareStatement(query2);
                ps2.setString(1, id);
                ps2.setString(2, memberID);    
                    
                     if(ps2.executeUpdate()>0){
                     
                         JOptionPane.showMessageDialog(null,"Book is succussfully reserved");
                     
                     }
                    else{
                        JOptionPane.showMessageDialog(null,"Something Wrong");
                     }
                    
                    
                    
                
                    }
                            
                            else{
                            
                            JOptionPane.showMessageDialog(null,"This user has reserved maximum number of books");
                            
                            }
            }
            else{
                JOptionPane.showMessageDialog(null,"This user is not available");
            }

        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       }
       
       else if(available.equals("reserved")){
       
       JOptionPane.showMessageDialog(null,"This book is already reserved");
       }
       
       else {
       
       JOptionPane.showMessageDialog(null,"This book is not available to reserve");
       }
        
    }//GEN-LAST:event_btnBookReserveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member_Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member_Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member_Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member_Book_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member_Book_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookReserve;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvaialability;
    private javax.swing.JLabel lblBookAuthor;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookAvaialability;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookName;
    // End of variables declaration//GEN-END:variables
}
